# cargo-deny configuration for bitcoin-augur

[licenses]
# Confidence threshold for detecting license files
confidence-threshold = 0.9

# List of allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Zlib",
    "OpenSSL",
    "MPL-2.0",
]

# Exceptions for specific crates
# Many Unicode-related crates use Unicode-3.0 which isn't recognized by cargo-deny 0.14.x
exceptions = [
    { allow = ["Unicode-3.0"], name = "icu_collections" },
    { allow = ["Unicode-3.0"], name = "icu_locale_core" },
    { allow = ["Unicode-3.0"], name = "icu_normalizer" },
    { allow = ["Unicode-3.0"], name = "icu_normalizer_data" },
    { allow = ["Unicode-3.0"], name = "icu_properties" },
    { allow = ["Unicode-3.0"], name = "icu_properties_data" },
    { allow = ["Unicode-3.0"], name = "icu_provider" },
    { allow = ["Unicode-3.0"], name = "icu_provider_macros" },
    { allow = ["Unicode-3.0"], name = "litemap" },
    { allow = ["Unicode-3.0"], name = "potential_utf" },
    { allow = ["Unicode-3.0"], name = "tinystr" },
    { allow = ["Unicode-3.0"], name = "writeable" },
    { allow = ["Unicode-3.0"], name = "yoke" },
    { allow = ["Unicode-3.0"], name = "yoke-derive" },
    { allow = ["Unicode-3.0"], name = "zerofrom" },
    { allow = ["Unicode-3.0"], name = "zerofrom-derive" },
    # unicode-ident has dual license MIT/Apache-2.0 AND Unicode-3.0
    { allow = ["MIT", "Apache-2.0", "Unicode-3.0"], name = "unicode-ident" },
    { allow = ["CDLA-Permissive-2.0"], name = "webpki-roots" },
    { allow = ["Unicode-3.0"], name = "zerotrie" },
    { allow = ["Unicode-3.0"], name = "zerovec" },
]

[bans]
# Lint level for when multiple versions of the same dependency are detected
multiple-versions = "allow"

# Lint level for wildcards in dependencies
wildcards = "allow"

# Deny specific crates
deny = []

[advisories]
# Path to the advisory database
db-path = "~/.cargo/advisory-db"

# URL(s) to the advisory database
db-urls = ["https://github.com/rustsec/advisory-db"]

# Ignore specific advisories
ignore = [
    "RUSTSEC-2024-0436", # paste - unmaintained but used indirectly via statrs
]

[sources]
# Lint level for crates from unknown registries
unknown-registry = "warn"

# Lint level for crates from unknown git sources
unknown-git = "warn"

# Allow git sources
allow-git = []