# cargo-deny configuration for bitcoin-augur

[licenses]
# Confidence threshold for detecting license files
confidence-threshold = 0.9

# List of allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
    "Zlib",
    "OpenSSL",
    "MPL-2.0",
    "CDLA-Permissive-2.0",
]

# Exceptions for specific crates
exceptions = []

[bans]
# Lint level for when multiple versions of the same dependency are detected
multiple-versions = "allow"

# Lint level for wildcards in dependencies
wildcards = "allow"

# Deny specific crates
deny = []

[advisories]
# Path to the advisory database
db-path = "~/.cargo/advisory-db"

# URL(s) to the advisory database
db-urls = ["https://github.com/rustsec/advisory-db"]

# Ignore specific advisories
ignore = [
    "RUSTSEC-2024-0436", # paste - unmaintained but used indirectly via statrs
]

[sources]
# Lint level for crates from unknown registries
unknown-registry = "warn"

# Lint level for crates from unknown git sources
unknown-git = "warn"

# Allow git sources
allow-git = []