name: Test

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-nix:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: nix-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          nix-cargo-
    
    - name: Check formatting
      run: nix develop -c cargo fmt --all --check
    
    - name: Run clippy
      run: nix develop -c cargo clippy --all-targets -- -D warnings
    
    - name: Build
      run: nix develop -c cargo build --verbose
    
    - name: Run tests
      run: nix develop -c cargo test --verbose
    
    - name: Run doc tests
      run: nix develop -c cargo test --doc
    
    - name: Build documentation
      run: nix develop -c cargo doc --no-deps